#!/bin/sh
#
# Adam Tavares
# Feb 7, 2014
#
# Convert images into different formats
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
VERSION="ImageMagick-6.8.8-4"
IMAGE_MAGICK="$DIR/imagemagick/$VERSION"
JPGLIB="openjpeg-2.0.0"
PNGLIB="libpng-1.6.9"
TIFFLIB="tiff-4.0.3"
DELLIB="$DIR/imagemagick/lib" # Delegate library.  Delegates are image format libraries

exit_err() {
  [ $# -gt 0 ] && echo "fatal: $*" 1>&2
  exit 1
}
install() {
#	installDelegates
	installImagemagick
}
installImagemagick() {
	cd $DIR/imagemagick
	tar xvzf $VERSION.tar.gz
	cd $IMAGE_MAGICK
	./configure \
		LDFLAGS='-L/usr/local/lib' \
		CPPFLAGS='-I/usr/local/lib' \
		--prefix=/usr/local \
		--with-quantum-depth=16 \
		--disable-dependency-tracking \
		--without-perl \
		--with-png=yes \
		--with-jpeg=yes \
		--with-jp2=yes \
		--with-tiff=yes \
	make clean
	make check
	make
	make install
}

installPngLib() {
	# install png library
	cd $DIR/imagemagick
	tar xvzf $PNGLIB.tar.gz
	cd $PNGLIB
	./configure --prefix=/usr/local
	make clean
	make check
	make install
}

installTiffLib() {
	# install tiff library
	cd $DIR/imagemagick
	tar xvzf $TIFFLIB.tar.gz
	cd $TIFFLIB
	./configure --prefix=/usr/local
	make clean
	make check
	make install
}

installJpgLib() {
	# install jpeg library
	cd $DIR/imagemagick
	tar xvzf $JPGLIB.tar.gz
	cd $JPGLIB
	cmake .
	make clean
	make
	make check
	make install
}

installDelegates() {
	installPngLib
	installTiffLib
	installJpgLib
}
jpgToTiff() {
	SRC=$1
	OUT=$2
	pathCheck $2
	convert $SRC -compress jpeg -define tiff:tile-geometry=256x256 "ptif:${OUT}"
}
jp2ToJpeg() {
	SRC=$1
	OUT=$2
}
config() {
	convert -list configure
}
# Check the output path and make intermediate directories
pathCheck() {
	OUT=$1
	OUTPATH=$( dirname $OUT )
	if [ ! -d "$OUTPATH" ]; then
		echo "Output directory not found.  New directory created at $OUTPATH"
		mkdir -p $OUTPATH
	fi
}

# What shall I do for you, sire?
CMD=$(echo "$1" | sed 's/\/$//'); shift

# Well I gotta do something!
if [ -z "$CMD" ]; then
	exit_err "No command was specified"
fi

# Okay let's get configured...
export MAGICK_HOME="$DIR/imagemagick/build"
export PATH="$MAGICK_HOME/bin:$PATH"
LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$MAGICK_HOME/lib"
export LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH="$MAGICK_HOME/lib/"

if [ "$CMD" = "install" ]; then
	install
elif [ "$CMD" = "jpgToTiff" ]; then
	SRC=$(echo "$1" | sed 's/\/$//'); shift
	OUT=$(echo "$1" | sed 's/\/$//'); shift
	jpgToTiff $SRC $OUT
elif [ "$CMD" = "jp2ToJpeg" ]; then
	SRC=$(echo "$1" | sed 's/\/$//'); shift
	OUT=$(echo "$1" | sed 's/\/$//'); shift
	jp2ToJpeg $SRC $OUT
elif [ "$CMD" = "config" ]; then
	config
fi

